name: Deploy ELK Stack

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Close previous docker containers
        run: sudo docker compose down

      - name: Run docker with build
        run: sudo docker compose up --build -d
      - name: Check Docker Containers Status
        run: sudo docker ps -a
