name: Deploy ELK Stack

on:
  push:
    branches:
      - main # Adjust this to the branches you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Close previous docker containers
        run: sudo docker compose -f docker-compose.yml -p elk down

      - name: Run docker with build
        run: sudo docker compose -f docker-compose.yml -p elk up --build -d

      - name: List running containers # Diagnostic step
        run: docker ps

      - name: Check logs of a specific container # Optional, for specific container
        run: docker logs [CONTAINER_NAME_OR_ID]

      - name: Inspect specific container # Optional, to see why it might have exited
        run: docker inspect [CONTAINER_NAME_OR_ID]
