name: Deploy ELK Stack

on:
  push:
    branches:
      - main # Adjust this to the branches you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Close previous docker containers
        run: sudo docker compose -f docker-compose.yml -p elk down

      - name: Run docker with build
        run: sudo docker compose -f docker-compose.yml -p elk up --build -d
