name: Run production elk
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Close previous docker containers
        run: sudo docker compose -f docker-compose.yml -p elk down
      - name: Run docker with build
        run: sudo docker compose -f docker-compose.yml -p elk up --build -d
